# Generated by Django 4.2.1 on 2023-05-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_machine_date_alter_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
        ),
    ]
