# Generated by Django 4.2.1 on 2023-05-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_machine_date_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixels', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
        ),
    ]
