# Generated by Django 4.2.1 on 2023-05-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
